In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[7454, 118, 2185, 2372], [7454, 118, 2185, 2000], [7454, 3321, 2185, 9042], [8802, 260, 1324, 13, 7851], [8802, 260, 1324, 13, 9093], [4569, 7454, 3308, 2185, 2046], [6603, 4176, 561, 13]]


### Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7454  118 2185 2372]
 [   0    0    0    0 7454  118 2185 2000]
 [   0    0    0    0 7454 3321 2185 9042]
 [   0    0    0 8802  260 1324   13 7851]
 [   0    0    0 8802  260 1324   13 9093]
 [   0    0    0 4569 7454 3308 2185 2046]
 [   0    0    0    0 6603 4176  561   13]]


In [12]:
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

[[[-0.01497966 -0.02209729  0.04049749 -0.01207672 -0.01257583
   -0.04090361  0.0451687   0.0119756   0.00666837 -0.0346115 ]
  [-0.01497966 -0.02209729  0.04049749 -0.01207672 -0.01257583
   -0.04090361  0.0451687   0.0119756   0.00666837 -0.0346115 ]
  [-0.01497966 -0.02209729  0.04049749 -0.01207672 -0.01257583
   -0.04090361  0.0451687   0.0119756   0.00666837 -0.0346115 ]
  [-0.01497966 -0.02209729  0.04049749 -0.01207672 -0.01257583
   -0.04090361  0.0451687   0.0119756   0.00666837 -0.0346115 ]
  [ 0.01106085  0.03443127  0.04287466  0.01100413  0.02757939
   -0.00888072  0.02380431 -0.02916424  0.02082017  0.03355222]
  [ 0.04745102 -0.0092508   0.04053838 -0.02274023  0.03802487
    0.02892292 -0.01804813  0.02022345 -0.02642242  0.03927274]
  [ 0.01918459  0.00399876  0.02044112  0.00123014 -0.02099067
    0.03249015  0.04841563 -0.00486974  0.00444014  0.00498839]
  [-0.00080969 -0.00073294  0.01978716 -0.02777869  0.0225105
   -0.04890486 -0.02157568 -0.02953936  0.0488700

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 7454,  118, 2185, 2372])

In [17]:
print(model.predict(embedded_docs)[0])

[[-0.01497966 -0.02209729  0.04049749 -0.01207672 -0.01257583 -0.04090361
   0.0451687   0.0119756   0.00666837 -0.0346115 ]
 [-0.01497966 -0.02209729  0.04049749 -0.01207672 -0.01257583 -0.04090361
   0.0451687   0.0119756   0.00666837 -0.0346115 ]
 [-0.01497966 -0.02209729  0.04049749 -0.01207672 -0.01257583 -0.04090361
   0.0451687   0.0119756   0.00666837 -0.0346115 ]
 [-0.01497966 -0.02209729  0.04049749 -0.01207672 -0.01257583 -0.04090361
   0.0451687   0.0119756   0.00666837 -0.0346115 ]
 [ 0.01106085  0.03443127  0.04287466  0.01100413  0.02757939 -0.00888072
   0.02380431 -0.02916424  0.02082017  0.03355222]
 [ 0.04745102 -0.0092508   0.04053838 -0.02274023  0.03802487  0.02892292
  -0.01804813  0.02022345 -0.02642242  0.03927274]
 [ 0.01918459  0.00399876  0.02044112  0.00123014 -0.02099067  0.03249015
   0.04841563 -0.00486974  0.00444014  0.00498839]
 [-0.00080969 -0.00073294  0.01978716 -0.02777869  0.0225105  -0.04890486
  -0.02157568 -0.02953936  0.04887004  0.01925193]]